export const countries = [
  'Aland Islands',
  'Albania',
  'Afghanistan',
  'Algeria',
  'Andorra',
  'American Samoa',
  'Anguilla',
  'Antigua And Barbuda',
  'Argentina',
  'Antarctica',
  'Armenia',
  'Angola',
  'Australia',
  'Aruba',
  'Austria',
  'Bahamas The',
  'Bahrain',
  'Bangladesh',
  'Azerbaijan',
  'Barbados',
  'Belarus',
  'Belgium',
  'Benin',
  'Belize',
  'Bermuda',
  'Bonaire, Sint Eustatius and Saba',
  'Bolivia',
  'Botswana',
  'Bhutan',
  'Bouvet Island',
  'Bosnia and Herzegovina',
  'British Indian Ocean Territory',
  'Brunei',
  'Brazil',
  'Bulgaria',
  'Burkina Faso',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Burundi',
  'Cayman Islands',
  'Central African Republic',
  'Cape Verde',
  'Chad',
  'Chile',
  'Christmas Island',
  'Cocos (Keeling) Islands',
  'China',
  'Comoros',
  'Colombia',
  'Cook Islands',
  'Costa Rica',
  'Congo',
  'Cote D`Ivoire',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Curaçao',
  'Czech Republic',
  'Democratic Republic of the Congo',
  'Djibouti',
  'Denmark',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'East Timor',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Ethiopia',
  'Faroe Islands',
  'Falkland Islands',
  'Estonia',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Gambia The',
  'Germany',
  'Georgia',
  'Ghana',
  'Gibraltar',
  'Gabon',
  'Greece',
  'Greenland',
  'Grenada',
  'Fiji Islands',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey and Alderney',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard Island and McDonald Islands',
  'Honduras',
  'Hong Kong S.A.R.',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Jamaica',
  'Italy',
  'Israel',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Lebanon',
  'Lesotho',
  'Latvia',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Macau S.A.R.',
  'Madagascar',
  'Luxembourg',
  'Macedonia',
  'Malaysia',
  'Malawi',
  'Maldives',
  'Laos',
  'Mali',
  'Man (Isle of)',
  'Malta',
  'Martinique',
  'Mauritania',
  'Mayotte',
  'Mexico',
  'Marshall Islands',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Mauritius',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Mozambique',
  'Niger',
  'Niue',
  'Norfolk Island',
  'Northern Mariana Islands',
  'North Korea',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestinian Territory Occupied',
  'Papua new Guinea',
  'Paraguay',
  'Panama',
  'Nigeria',
  'Philippines',
  'Peru',
  'Pitcairn Island',
  'Poland',
  'Portugal',
  'Qatar',
  'Puerto Rico',
  'Reunion',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Helena',
  'Saint Kitts And Nevis',
  'Saint Lucia',
  'Saint Pierre and Miquelon',
  'Saint Vincent And The Grenadines',
  'Saint-Martin (French part)',
  'Saint-Barthelemy',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Sint Maarten (Dutch part)',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia',
  'South Korea',
  'Spain',
  'South Sudan',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Swaziland',
  'Svalbard And Jan Mayen Islands',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Tokelau',
  'Trinidad And Tobago',
  'Tonga',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks And Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United States',
  'United Kingdom',
  'United States Minor Outlying Islands',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City State (Holy See)',
  'Venezuela',
  'Vietnam',
  'Virgin Islands (British)',
  'Virgin Islands (US)',
  'Wallis And Futuna Islands',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe'
]
